import type { RuleSet } from './types.js';

export const RULESET_DRAFT: RuleSet = {
  name: 'aarogyarekha-layered',
  version: '0.1.1',
  status: 'draft',
  provenance: 'Transcribed from memory; unverified against primary sources; no clinical review. Do not use for real patients.',
  insufficientDataTier: 3,
  potentialTierCap: 1,

  floors: [
    { id: 'ETAT-E1', sign: 'airway_obstructed_or_not_breathing', tier: 1, population: 'any', label: 'Airway obstructed or not breathing', question: 'Is the airway blocked, or has breathing stopped?', source: 'WHO ETAT emergency signs' },
    { id: 'ETAT-E2', sign: 'severe_respiratory_distress', tier: 1, population: 'any', label: 'Severe breathing difficulty', question: 'Is the patient struggling severely to breathe (gasping, very fast, or chest drawing in hard)?', source: 'WHO ETAT emergency signs' },
    { id: 'ETAT-E3', sign: 'central_cyanosis', tier: 1, population: 'any', label: 'Blue or grey lips or tongue', question: 'Are the lips or tongue blue or grey?', source: 'WHO ETAT emergency signs' },
    { id: 'ETAT-E4', sign: 'shock_signs', tier: 1, population: 'any', label: 'Signs of poor circulation (cold hands or feet, weak fast pulse, slow capillary refill)', question: 'Are the hands and feet cold, with a weak fast pulse or slow capillary refill?', source: 'WHO ETAT emergency signs' },
    { id: 'ETAT-E5', sign: 'unconscious_or_convulsing_now', tier: 1, population: 'any', label: 'Unconscious, or having a convulsion now', question: 'Is the patient unconscious, or having a convulsion right now?', source: 'WHO ETAT emergency signs' },
    { id: 'ETAT-E6', sign: 'severe_fluid_loss_signs', tier: 1, population: 'child_under_5', label: 'Signs of severe fluid loss with diarrhoea (lethargy, sunken eyes, very slow skin pinch)', question: 'With diarrhoea: is the child very sleepy or limp, with sunken eyes or a very slow skin pinch?', source: 'WHO ETAT emergency signs' },
    { id: 'IMNCI-G1', sign: 'unable_to_drink_or_breastfeed', tier: 2, population: 'child_under_5', label: 'Unable to drink or breastfeed', question: 'Is the child unable to drink or breastfeed?', source: 'IMNCI general danger signs' },
    { id: 'IMNCI-G2', sign: 'vomits_everything', tier: 2, population: 'child_under_5', label: 'Vomits everything', question: 'Does the child vomit everything?', source: 'IMNCI general danger signs' },
    { id: 'IMNCI-G3', sign: 'convulsions_this_illness', tier: 2, population: 'child_under_5', label: 'Convulsions during this illness', question: 'Has the child had convulsions during this illness?', source: 'IMNCI general danger signs' },
    { id: 'IMNCI-G4', sign: 'lethargic', tier: 2, population: 'child_under_5', label: 'Unusually sleepy or hard to wake', question: 'Is the child unusually sleepy or hard to wake?', source: 'IMNCI general danger signs' },
    { id: 'ETAT-P1', sign: 'tiny_infant_under_2_months', tier: 3, population: 'child_under_5', label: 'Infant under 2 months', question: 'Is the infant under 2 months old?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P2', sign: 'very_high_fever_child', tier: 3, population: 'child_under_5', label: 'Very high fever (as judged by the health worker)', question: "Is the fever very high, in the health worker's judgement?", source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P3', sign: 'major_trauma_or_burns', tier: 3, population: 'child_under_5', label: 'Major injury or burns', question: 'Has the child had a major injury or burn?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P4', sign: 'severe_pallor', tier: 3, population: 'child_under_5', label: 'Severe paleness', question: 'Is the child severely pale?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P5', sign: 'poisoning_reported', tier: 3, population: 'child_under_5', label: 'Possible poisoning reported', question: 'Could the child have swallowed something poisonous?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P6', sign: 'severe_pain', tier: 3, population: 'child_under_5', label: 'Severe pain', question: 'Is the child in severe pain?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P7', sign: 'breathing_difficulty_not_severe', tier: 3, population: 'child_under_5', label: 'Some breathing difficulty', question: 'Is the child having some difficulty breathing, but not severe?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P8', sign: 'restless_or_irritable', tier: 3, population: 'child_under_5', label: 'Continuously restless or irritable', question: 'Is the child restless or irritable all the time?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P9', sign: 'severe_visible_wasting', tier: 3, population: 'child_under_5', label: 'Severe visible wasting', question: 'Does the child look severely wasted (very thin)?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P10', sign: 'swelling_both_feet', tier: 3, population: 'child_under_5', label: 'Swelling of both feet', question: 'Are both feet swollen?', source: 'WHO ETAT priority signs' },
    { id: 'ETAT-P11', sign: 'urgent_referral_in', tier: 3, population: 'child_under_5', label: 'Sent in as an urgent referral', question: 'Was the child sent in as an urgent referral?', source: 'WHO ETAT priority signs' },
    { id: 'NHM-M1', sign: 'convulsions_in_pregnancy', tier: 1, population: 'pregnant', label: 'Convulsions in pregnancy', question: 'Is she having convulsions?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M2', sign: 'heavy_vaginal_bleeding', tier: 1, population: 'pregnant', label: 'Heavy vaginal bleeding', question: 'Is she bleeding heavily from the vagina?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M3', sign: 'severe_headache_blurred_vision', tier: 2, population: 'pregnant', label: 'Severe headache or blurred vision', question: 'Does she have a severe headache or blurred vision?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M4', sign: 'severe_abdominal_pain', tier: 2, population: 'pregnant', label: 'Severe abdominal pain', question: 'Does she have severe abdominal pain?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M5', sign: 'reduced_fetal_movement', tier: 2, population: 'pregnant', label: 'Baby moving less or not at all', question: 'Is the baby moving less than usual, or not at all?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M6', sign: 'leaking_fluid_or_labour_pains', tier: 2, population: 'pregnant', label: 'Leaking fluid or regular labour pains', question: 'Is fluid leaking, or does she have regular labour pains?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M7', sign: 'fever_in_pregnancy', tier: 2, population: 'pregnant', label: 'Fever in pregnancy', question: 'Does she have a fever?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M8', sign: 'breathing_difficulty_pregnancy', tier: 2, population: 'pregnant', label: 'Difficulty breathing in pregnancy', question: 'Is she having difficulty breathing?', source: 'NHM maternal danger signs' },
    { id: 'NHM-M9', sign: 'any_vaginal_bleeding', tier: 2, population: 'pregnant', label: 'Vaginal bleeding in pregnancy', question: 'Is there any vaginal bleeding?', source: 'NHM maternal danger signs' },
  ],

  pregnancyHypertension: {
    id: 'WHO-PREG-BP', sbp: 160, dbp: 110, tier: 2,
    label: 'Blood pressure in the severe range for pregnancy (as recorded)',
    source: 'WHO severe hypertension in pregnancy (>=160 systolic or >=110 diastolic)  [verify]',
  },

  news2: {
    minAgeYears: 16,
    source: 'Royal College of Physicians NEWS2 (2017), SpO2 Scale 1. Not for children or pregnancy. Scale 2 (clinician-prescribed target) is not supported.',
    bands: {
      resp_rate_pm:     [{ upTo: 8, score: 3 }, { upTo: 11, score: 1 }, { upTo: 20, score: 0 }, { upTo: 24, score: 2 }, { score: 3 }],
      spo2_pct:         [{ upTo: 91, score: 3 }, { upTo: 93, score: 2 }, { upTo: 95, score: 1 }, { score: 0 }],
      bp_systolic_mmhg: [{ upTo: 90, score: 3 }, { upTo: 100, score: 2 }, { upTo: 110, score: 1 }, { upTo: 219, score: 0 }, { score: 3 }],
      pulse_bpm:        [{ upTo: 40, score: 3 }, { upTo: 50, score: 1 }, { upTo: 90, score: 0 }, { upTo: 110, score: 1 }, { upTo: 130, score: 2 }, { score: 3 }],
      temperature_c:    [{ upTo: 35.0, score: 3 }, { upTo: 36.0, score: 1 }, { upTo: 38.0, score: 0 }, { upTo: 39.0, score: 1 }, { score: 2 }],
    },
    consciousnessNotAlert: 3,
    supplementalOxygen: 2,
    maxPerParam: { resp_rate_pm: 3, spo2_pct: 3, bp_systolic_mmhg: 3, pulse_bpm: 3, temperature_c: 2, consciousness: 3, oxygen: 2 },
    tierMap: {
      aggregateHighMin: 7, aggregateHighTier: 1,
      aggregateMediumMin: 5, aggregateMediumTier: 2,
      singleRedScore: 3, singleRedTier: 2,
      lowMin: 1, lowTier: 3,
      zeroTier: 4,
    },
  },

  vulnerable: { ageUnder: 5, ageOver: 65 },
};
